version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Scripts SQL de inicialización

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  persona-service:
    build:
      context: ./persona-service
    container_name: persona-service
    ports:
      - "8089:8089"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./persona-service/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banco_service_db?currentSchema=cliente
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  cuenta-service:
    build:
      context: ./cuenta-service
    container_name: cuenta-service
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./cuenta-service/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banco_service_db?currentSchema=cuenta_movimiento
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

volumes:
  postgres_data:
